feature: replace map structure
UrbVerde/urbverde-ui pull request #5
Opened 2024-12-19 15:19 UTC by LippeOli

Adds map functionality to the platform, integrating search and map features into a new structure in the development branch. This update includes the following improvements:

- Added map components: Navbar, Legend, and MapGenerator.
- Created a pages folder to manage app redirections.
- Fixed and adjusted the front-end of several components to enhance the user interface.

2024-12-19 16:02 UTC, analiviagarbin approved these changes

2024-12-19 16:14 UTC, FelipeCorerato requested changes

2024-12-19 16:14 UTC, FelipeCorerato commented on src/assets/styles/custom.scss
> +@import 'bootstrap/scss/bootstrap';
Muito boa a iniciativa de concentrar os tokens usados!

2024-12-19 16:14 UTC, FelipeCorerato commented on src/assets/styles/custom.scss
> +.caption-regular {
Para evitar um arquivo muito longo, acredito que faça sentido separar em colors, font, spacing, etc para tratar cada um dos contextos.

2024-12-19 16:14 UTC, FelipeCorerato commented on src/components/map/mapGenerator.vue
> +  <!--left 148  -> 188-->
O que significa?

2024-12-19 16:14 UTC, FelipeCorerato commented on src/components/side_bar/SideBar.vue
> +
Rode o eslint pra evitar essas linhas vazias desnecessárias.

2024-12-19 16:14 UTC, FelipeCorerato commented on src/components/side_bar/buttons/MinimizeButton.vue
> +import minimizeImage from '@/assets//icons/minimize.svg';
Acredito que tenha uma barra "/" a mais aqui

2024-12-19 16:14 UTC, FelipeCorerato commented on src/components/side_bar/drop_down/NavbarItemDropdown.vue
> +import collapseIcon from '../../../assets/icons/collapse.svg';
Boa ideia essa mudança de estrutura dos icons!

2024-12-19 16:14 UTC, FelipeCorerato commented on src/components/side_bar/drop_down/NavbarItemDropdown.vue
> +import bike from "../../../assets/icons/bike.svg"
Padronize os " com ' pelo eslint

2024-12-21 15:56 UTC, LippeOli commented on src/components/map/mapGenerator.vue
> +  <!--left 148  -> 188-->
era especificacoes pra responsividade  do mapa

2024-12-21 20:43 UTC, merged